# Sample Code for lecture~06 
Heterogeneous Computing for AI [PG2015]


Raghava Mukkamala (rrm.digi@cbs.dk, Copenhagen Business School, Denmark

https://raghavamukkamala.github.io/

### Motivation for NumPy Arrays
[taken from datacamp exercises]

In [1]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]

weight = [65.4, 59.2, 63.6, 88.4, 68.7]

# You want to calculate BMI = weight / height ** 2
#bmi = weight / height ** 2

bmi = []

for i in range(len(weight)):
    bmi.append(weight[i] / height[i] ** 2)

print('bmi: ', bmi)
    

bmi:  [21.85171572722109, 20.97505668934241, 21.750282138093777, 24.74734749867025, 21.44127836209856]


In [2]:
import numpy as np

### with NumPy Arrays
[taken from datacamp exercises]

In [3]:


np_height = np.array(height)

print('np_height: ', np_height)

np_weight = np.array(weight)

print('np_weight: ', np_weight)

np_bmi = np_weight / np_height ** 2

print('np_bmi: ', np_bmi)

np_height ** 2

np_height:  [1.73 1.68 1.71 1.89 1.79]
np_weight:  [65.4 59.2 63.6 88.4 68.7]
np_bmi:  [21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


array([2.9929, 2.8224, 2.9241, 3.5721, 3.2041])

## Fixed-Type Arrays in Python

Python offers several different options for storing data in efficient, fixed-type data buffers.
The built-in ``array`` module (available since Python 3.3) can be used to create dense arrays of a uniform type:

In [4]:
import array

L = list(range(10))
print('Python List L:', L)

A = array.array('i', L)

print('A:', A)
del(L)

print('Fixed Array A:', A)
#A[0] = 'raghava'




Python List L: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
A: array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Fixed Array A: array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### NumPy Arrays Creation

In [8]:
# integer array:
npar =np.array([1, 4, 2, 5, 3] , dtype='float32')
print(npar.dtype)
print(type(npar[0]))
print(npar)

float32
<class 'numpy.float32'>
[1. 4. 2. 5. 3.]


In [9]:
# You can specify the type explicitly.
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [10]:
# Create a 3x5 array filled with 3.14
ar = np.full((3, 5), 3.14)

print(ar)

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


In [13]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((5, 10))


array([[0.38816691, 0.67748643, 0.91232966, 0.87367696, 0.0416137 ,
        0.28228872, 0.40088386, 0.04651695, 0.83048968, 0.83596623],
       [0.13496299, 0.74361239, 0.46183999, 0.42857522, 0.24810379,
        0.39752209, 0.60242277, 0.40520688, 0.13446999, 0.13097567],
       [0.17945845, 0.84395246, 0.48046957, 0.63137191, 0.78621774,
        0.86799571, 0.25376602, 0.40443385, 0.59662433, 0.04712645],
       [0.7087056 , 0.55858991, 0.0548699 , 0.18169064, 0.43102367,
        0.68570693, 0.14323918, 0.28395044, 0.5250495 , 0.73560339],
       [0.82578188, 0.9845125 , 0.7245485 , 0.94938107, 0.18165733,
        0.18412556, 0.20429389, 0.82071374, 0.38057161, 0.39757136]])

### Create random values normally distributed

In [17]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1

onedim = np.random.normal(50, 3, 5)

print(onedim)

threedim = np.random.normal(99, 15, (2, 3, 5))

print(threedim)

#threedim[0:2,1,1]


[46.98586708 50.50531182 48.54956719 52.81174252 52.15912529]
[[[104.33225852  87.33642747  93.57980416  80.96730679  93.07587804]
  [ 65.27712768  77.22941385  94.92511766 113.02298673  86.72711804]
  [ 68.98449194  94.69797844  98.19748273 104.92301604 114.39230949]]

 [[ 79.15391623  93.21592994  69.89853856  87.09004245  95.68209727]
  [ 95.75993853 115.51000498 113.08776946 133.77312458  67.10017663]
  [ 90.24992304  97.80166542  84.31943129  89.89047101  92.41628589]]]


### Array Creation Examples

In [7]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

# syntax:
# numpy.random.randint(low, high=None, size=None, dtype='l')

x1 = np.random.randint(5,10, size=6)  # One-dimensional array

x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array

x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
x3

print('x1', x1)

print('x2', x2)

print('x3', x3)

x1 [9 5 8 8 8 6]
x2 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
x3 [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [23]:
x4 = np.random.randint(100, size=(3, 4, 5))  # Three-dimensional array

x5 = np.random.randint(90, 100, size=(3, 4, 5))  # Three-dimensional array

print('x4:', x4)

print('x5:', x5)

x6 = x4 - x5

print('x6:', x6)

x7 = x4 ** 5

print('x7:', x7)

x4: [[[38 39 99 21 78]
  [55  8 31 25  3]
  [65 94 82 66 12]
  [97 71  8 67 74]]

 [[52 78 36 28 82]
  [85 63 86 95 41]
  [16  2  4 21 60]
  [91 18 12 27 93]]

 [[11  5 19 48 67]
  [32 31 67 81 13]
  [ 5 90 19  2 92]
  [66 20 90 20 35]]]
x5: [[[92 90 92 94 98]
  [92 90 94 92 93]
  [93 99 92 94 92]
  [99 98 98 96 94]]

 [[90 95 91 93 91]
  [98 99 99 98 92]
  [91 91 92 99 92]
  [92 97 92 98 92]]

 [[98 91 95 97 98]
  [90 94 99 94 99]
  [97 93 96 98 97]
  [91 92 92 97 99]]]
x6: [[[-54 -51   7 -73 -20]
  [-37 -82 -63 -67 -90]
  [-28  -5 -10 -28 -80]
  [ -2 -27 -90 -29 -20]]

 [[-38 -17 -55 -65  -9]
  [-13 -36 -13  -3 -51]
  [-75 -89 -88 -78 -32]
  [ -1 -79 -80 -71   1]]

 [[-87 -86 -76 -49 -31]
  [-58 -63 -32 -13 -86]
  [-92  -3 -77 -96  -5]
  [-25 -72  -2 -77 -64]]]
x7: [[[  79235168   90224199 9509900499    4084101 2887174368]
  [ 503284375      32768   28629151    9765625        243]
  [1160290625 7339040224 3707398432 1252332576     248832]
  [8587340257 1804229351      32768 135012510

### Array Shape, Dimension and Size

In [9]:
print("x3 ndim: ", x3.ndim)

print("x1 shape:", x1.shape)

print("x2 shape:", x2.shape)

print("x3 shape:", x3.shape)

print("x3 size: ", x3.size)

x3 ndim:  3
x1 shape: (6,)
x2 shape: (3, 4)
x3 shape: (3, 4, 5)
x3 size:  60


## Reshape functionality

In [29]:
o_array = np.arange(90)

print('o_array:',o_array)

re_array = o_array.reshape((9,5, 2))

print('re_array', re_array)

o_array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89]
re_array [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]

 [[30 31]
  [32 33]
  [34 35]
  [36 37]
  [38 39]]

 [[40 41]
  [42 43]
  [44 45]
  [46 47]
  [48 49]]

 [[50 51]
  [52 53]
  [54 55]
  [56 57]
  [58 59]]

 [[60 61]
  [62 63]
  [64 65]
  [66 67]
  [68 69]]

 [[70 71]
  [72 73]
  [74 75]
  [76 77]
  [78 79]]

 [[80 81]
  [82 83]
  [84 85]
  [86 87]
  [88 89]]]


### Array axes and reduction such as sum etc.
https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html


In [10]:

# Create a array of integers
one_dim_array = np.arange(1,13)
# reshape the one dim array to two array..
two_dim_array =np.reshape(one_dim_array, (3,4))

print('two_dim_array: \n',two_dim_array)


#
sum_none =np.sum(two_dim_array, axis=None)

print('sum_none along axix= None: ', sum_none)




two_dim_array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
sum_none along axix= None:  78


In [11]:
sum_zero =np.sum(two_dim_array, axis=0)

print('sum_zero along axix= 0: ', sum_zero)

print('two_dim_array: \n',two_dim_array)

sum_axis_one =np.sum(two_dim_array, axis=1)

print('sum_one along axis = 1: ', sum_axis_one)


sum_zero along axix= 0:  [15 18 21 24]
two_dim_array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
sum_one along axis = 1:  [10 26 42]


In [12]:
prod_axis_zero =np.prod(two_dim_array, axis=0)

print('prod_axis_zero along axis = 0: ', prod_axis_zero)

print('two_dim_array: \n',two_dim_array)

prod_axis_one =np.prod(two_dim_array, axis=1)

print('prod_axis_one along axis = 1: ', prod_axis_one)


prod_axis_zero along axis = 0:  [ 45 120 231 384]
two_dim_array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
prod_axis_one along axis = 1:  [   24  1680 11880]


In [13]:
# Create a array of integers
one_dim_array = np.arange(1,13)

print('one_dim_array:', one_dim_array)

# reshape the one dim array to two array..
two_dim_array =np.reshape(one_dim_array, (3,4))

print('two_dim_array: \n',two_dim_array)


one_dim_array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
two_dim_array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
